// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKe2vbjyoAQINmaWlblGz4VzcH-t1pZDI',
    appId: '1:115894276217:web:32739cd1cc913855b8c4a8',
    messagingSenderId: '115894276217',
    projectId: 'spotifyaslicilegon',
    authDomain: 'spotifyaslicilegon.firebaseapp.com',
    storageBucket: 'spotifyaslicilegon.firebasestorage.app',
    measurementId: 'G-891ELTSNH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6VsEGx9xT-nKsXztcmgw37NmpZGF3i4I',
    appId: '1:115894276217:android:2ae6f5cbeed01bfeb8c4a8',
    messagingSenderId: '115894276217',
    projectId: 'spotifyaslicilegon',
    storageBucket: 'spotifyaslicilegon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5fS_vrXWoFQm_-n_cPWQHlCmMobR0-jY',
    appId: '1:115894276217:ios:2caef57ccaa7b16bb8c4a8',
    messagingSenderId: '115894276217',
    projectId: 'spotifyaslicilegon',
    storageBucket: 'spotifyaslicilegon.firebasestorage.app',
    iosBundleId: 'com.example.uas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5fS_vrXWoFQm_-n_cPWQHlCmMobR0-jY',
    appId: '1:115894276217:ios:2caef57ccaa7b16bb8c4a8',
    messagingSenderId: '115894276217',
    projectId: 'spotifyaslicilegon',
    storageBucket: 'spotifyaslicilegon.firebasestorage.app',
    iosBundleId: 'com.example.uas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKe2vbjyoAQINmaWlblGz4VzcH-t1pZDI',
    appId: '1:115894276217:web:c72abdbe0f0046b3b8c4a8',
    messagingSenderId: '115894276217',
    projectId: 'spotifyaslicilegon',
    authDomain: 'spotifyaslicilegon.firebaseapp.com',
    storageBucket: 'spotifyaslicilegon.firebasestorage.app',
    measurementId: 'G-GKR5NLJ67J',
  );
}
